version: '3.8'
services:
 node_app: 
  container_name: node_app
  build: .
  image: ecommerce/node_sequelize_postgres
  ports:
     - "8000:8000"
  environment:
    - PG_DB= node_sequelize_postgres
    - PG_USER= postgres
    - PG_PASSWORD= seef8*+*88
    - PG_HOST= postgres_db
  depends_on: 
    - postgres_db
  restart: always      
 #postgres service 
 postgres_db:
    container_name: postgres_db
    image: postgres:13
    ports: 
      - "5432:5432"
    environment:
     - POSTGRES_USER= postgres   
     - POSTGRES_PASSWORD= seef8*+*88
     - POSTGRES_DB= node_sequelize_postgres
    volumes:
       - node_db_data:/var/lib/postgresql/data
volumes:
  node_db_data: {}             
                   